# Arquivo a ser utilizado pelo plugin REST Client do VSCode para testar a API
# Abrir o arquivo e usar Ctrl-Alt-R para enviar a requisição
PUT http://0.0.0.0:5103/v1/veiculos/entradaplaca
Content-Type: application/json

{
  "placa": "CCC-1235",
  "idCamera": 1,
  "dataEntrada": "2025-07-04T18:41:00Z"
}
